Testing
Emmanuelaaron/TodoListProject pull request #6
Opened 2021-08-25 23:36 UTC by Emmanuelaaron

## In this project we tested the todo list using jest

### Tools and Techs used
- Jest

## how to test
- clone the repo
- checkout out to the testing branch ```git checkout testing```
-  run  ```npm install```
- run  ```npm run test```

All tests shoud be passin

2021-08-25 23:57 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 23:57 UTC, vichuge commented on test/deleteTodo.test.js
> +});
- [x] Good job doing a test for delete an element, now, let's add another test that checks how the IDs work when you, for example, delete the second element in a list for 3, and then the 3rd element now has the id 2 for example. 🦊

2021-08-25 23:57 UTC, vichuge commented on test/createTodo.test.js
> +});
- [x] Uses mock for functions that used localStorage, DOM or external APIs. I observe you have the localStorage use on index.js but please, add more tests when you prove that update the localStorage status. This part is important because localStorage should work well on your application. Test localStorage when you delete an element too. 🐱 
- [x] In both scripts (add and delete) you need to test all pure functions that are implied for add and delete an element, please, add more tests that check every function inside the add/delete functionality. 🐶

2021-08-26 20:29 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @Emmanuelaaron, @Chike1990 &  @JuliCarracedo,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-26 20:34 UTC, merged